import { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'sr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, fallback?: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'explore.all': 'Explore all',
    'stays': 'stays',
    'stay': 'stay',
    'search.results': 'Search Results for',
    'properties': 'Properties',
    'no.properties': 'No properties found',
    'try.adjusting': 'Try adjusting your search criteria',
    'find.adventure': 'Find your next adventure',
    'discover.places': 'Discover unique places to stay across the Balkans',
    'become.host': 'Become a Host',
    'my.bookings': 'My Bookings',
    'no.bookings': 'No bookings yet',
    'no.bookings.desc': 'Start exploring and book your first stay!',
    'no.bookings.found': 'No bookings found',
    'explore.properties': 'Explore Properties',
    'search.bookings': 'Search bookings',
    'bookings.all': 'All',
    'bookings.upcoming': 'Upcoming',
    'bookings.completed': 'Completed',
    'bookings.cancelled': 'Cancelled',
    'booking.status.upcoming': 'Upcoming',
    'booking.status.completed': 'Completed',
    'booking.status.cancelled': 'Cancelled',
    'cancel.booking.confirm': 'Are you sure you want to cancel this booking?',
    'booking.cancelled': 'Booking cancelled',
    'cancel': 'Cancel',
    'cancel.booking': 'Cancel Booking',
    'view.property': 'View Property',
    'saved.properties': 'Saved Properties',
    'saved.property': 'saved property',
    'profile': 'Profile',
    'welcome': 'Welcome',
    'member.since': 'Member since',
    'total.spent': 'Total Spent',
    'quick.actions': 'Quick Actions',
    'list.your.place': 'List your place',
    'find.stays': 'Find stays',
    'favorite.destinations': 'Favorite Destinations',
    'saved': 'saved',
    'active': 'active',
    'explore': 'Explore',
    'select.language': 'Select language',
    'light': 'Light',
    'dark': 'Dark',
    'language': 'Language',
    'theme': 'Theme',
    'no.favorites': 'No favorites yet',
    'no.favorites.desc': 'Start exploring and save your favorite properties!',
    'removed.from.favorites': 'Removed from favorites',
    'remove.from.favorites': 'Remove from favorites',
    'added.to.favorites': 'Added to favorites',
    'recent.views': 'Recently Viewed',
    'clear.recent.views': 'Clear recent views',
    'host.dashboard': 'Host Dashboard',
    'settings': 'Settings',
    'log.out': 'Log out',
    'account': 'Account',
    'edit.profile': 'Edit Profile',
    'display.name': 'Display Name',
    'save': 'Save',
    'your.name': 'Your name',
    'saving': 'Saving...',
    'profile.updated': 'Profile updated',
    'log.in': 'Log in',
    'sign.up': 'Sign up',
    'sign.in': 'Sign in',
    'register': 'Register',
    'email.address': 'Email address',
    'password': 'Password',
    'full.name': 'Full name',
    'login.title': 'Log in to your account',
    'login.subtitle': 'Welcome back',
    'register.title': 'Create an account',
    'register.subtitle': 'Join Nexora to book and list stays',
    'no.account': "Don't have an account?",
    'have.account': 'Already have an account?',
    'login.failed': 'Invalid email or password',
    'register.failed': 'Registration failed. Try again.',
    'register.success': 'Account created successfully',
    'login.required': 'Please log in to continue',
    'my.listings': 'My Listings',
    'host.reservations': 'Reservations',
    'host.reservations.short': 'Reservations for your listings',
    'host.reservations.desc': 'Overview of reservations for your published listings.',
    'host.no.reservations': 'No reservations yet',
    'host.no.reservations.desc': 'When someone books your listing, it will appear here.',
    'host.guest': 'Guest',
    'host.booked': 'booked',
    'add.property.requires.login': 'Log in to add your property',
    'reserve.requires.login': 'Log in to reserve',
    'delete.account': 'Delete account',
    'delete.account.desc': 'Permanently delete your account and all associated data. This cannot be undone.',
    'delete.account.confirm': 'Are you sure? Type "DELETE" to confirm.',
    'delete.account.done': 'Account deleted. You have been signed out.',
    'night': 'night',
    'anywhere': 'Anywhere',
    'any.week': 'Any week',
    'add.guests': 'Add guests',
    'search': 'Search',
    'search.destinations': 'Search destinations...',
    // Categories
    'all': 'All',
    'mansions': 'Mansions',
    'cabins': 'Cabins',
    'beach': 'Beach',
    'mountains': 'Mountains',
    'city': 'City',
    'lofts': 'Lofts',
    'countryside': 'Countryside',
    'camping': 'Camping',
    // Filters
    'filters': 'Filters',
    'reset': 'Reset',
    'sort.by': 'Sort by',
    'most.popular': 'Most Popular',
    'highest.rated': 'Highest Rated',
    'price.low.high': 'Price: Low to High',
    'price.high.low': 'Price: High to Low',
    'price.per.night': 'Price per night',
    'bedrooms': 'Bedrooms',
    'beds': 'Beds',
    'bathrooms': 'Bathrooms',
    'guests': 'Guests',
    'amenities': 'Amenities',
    'any': 'Any',
    'guest': 'guest',
    'guests.plural': 'guests',
    // Property Detail
    'back': 'Back',
    'reviews': 'reviews',
    'no.reviews.yet': 'No reviews yet',
    'leave.review': 'Leave a review',
    'login.to.review': 'Log in to leave a review',
    'submit.review': 'Submit review',
    'your.rating': 'Your rating',
    'your.review': 'Your review',
    'review.submitted': 'Review submitted',
    'review.failed': 'Failed to submit review',
    'already.reviewed': 'You already reviewed this property',
    'hosted.by': 'Hosted by',
    'superhost': 'Superhost',
    'responds': 'Responds',
    'response.rate': 'response rate',
    'what.place.offers': 'What this place offers',
    'check.in.out': 'Check-in & Check-out',
    'check.in': 'Check-in',
    'check.out': 'Check-out',
    'check.in.date': 'Check-in date',
    'check.out.date': 'Check-out date',
    'add.dates': 'Add dates',
    'reserve': 'Reserve',
    'reserving': 'Reserving...',
    'reservation.successful': 'Reservation successful!',
    'reservation.failed': 'Reservation failed. Please try again.',
    'dates.unavailable': 'Selected dates are no longer available.',
    'select.dates.first': 'Please select check-in and check-out dates first',
    'check.email': 'Check your email for confirmation.',
    'total': 'Total',
    'cleaning.fee': 'Cleaning fee',
    'service.fee': 'Service fee',
    'copy.link': 'Copy link',
    'link.copied': 'Link copied!',
    'share.facebook': 'Share on Facebook',
    'share.twitter': 'Share on Twitter',
    'show.all.photos': 'Show all photos',
    'image.unavailable': 'Image unavailable',
    'property.not.found': 'Property not found',
    'property.not.exist': "The property you're looking for doesn't exist.",
    'go.home': 'Go Home',
    'page.not.found': 'Page not found',
    'page.not.found.desc': "The page you're looking for doesn't exist or has been moved.",
    'something.wrong': 'Something went wrong',
    'try.again': 'Please try again later.',
    'back.to.home': 'Back to Home',
    // Privacy Policy
    'privacy.policy.title': 'Privacy Policy',
    'last.updated': 'Last updated: January 2025',
    // Terms of Service
    'terms.of.service.title': 'Terms of Service',
    // Booking Calendar
    'adult': 'adult',
    'adults': 'adults',
    'child': 'child',
    'children': 'children',
    'approximate.prices': 'Approximate prices in BAM for a 1-night stay',
    'base': 'Base',
    'nights': 'nights',
    'months.ago': 'months ago',
    // Footer
    'support': 'Support',
    'help.center': 'Help Center',
    'safety.information': 'Safety Information',
    'cancellation.options': 'Cancellation Options',
    'contact.us': 'Contact Us',
    'hosting': 'Hosting',
    'host.resources': 'Host Resources',
    'community.forum': 'Community Forum',
    'hosting.responsibly': 'Hosting Responsibly',
    'about': 'About',
    'about.builtBy': 'Built by',
    'footer.builtBy': 'Built by',
    'how.it.works': 'How it works',
    'newsroom': 'Newsroom',
    'careers': 'Careers',
    'investors': 'Investors',
    'legal': 'Legal',
    'privacy.policy': 'Privacy Policy',
    'terms.of.service': 'Terms of Service',
    'all.rights.reserved': 'All rights reserved',
    // Help Center
    'help.center.title': 'Help Center',
    'find.answers': 'Find answers to common questions',
    'search.for.help': 'Search for help...',
    'frequently.asked': 'Frequently Asked Questions',
    'no.results': 'No results found. Try a different search term.',
    'assistant.title': 'Nexora Assistant',
    'assistant.subtitle': 'Ask about the platform and accommodation in the Balkans.',
    'assistant.placeholder': 'Ask about Nexora, bookings, help...',
    'assistant.welcome': 'Ask me anything about Nexora, bookings, or accommodation in the Balkans.',
    'assistant.error': 'Could not get a response. Try again or use Help / Contact.',
    'still.need.help': 'Still need help?',
    'support.available': 'Our support team is available 24/7 to assist you.',
    'contact.support': 'Contact Support',
    // Contact
    'contact.us.title': 'Contact Us',
    'here.to.help': "We're here to help! Get in touch with our team.",
    'email': 'Email',
    'phone': 'Phone',
    'office': 'Office',
    'support.hours': 'Support Hours',
    'support.hours.note': 'Support available on weekdays.',
    'send.message': 'Send us a Message',
    'name': 'Name',
    'subject': 'Subject',
    'message': 'Message',
    'send': 'Send Message',
    'message.sent': 'Message sent successfully!',
    'contact.success': 'Message sent. We will get back to you.',
    'contact.error': 'Failed to send. Please try again.',
    'contact.demo.note': 'Portfolio demo. Messages are stored in Supabase. Use the form to get in touch.',
    'contact.via.form': 'Via contact form',
    'contact.region': 'Balkans',
    'get.back': "We'll get back to you within 24 hours.",
    // Become Host
    'become.host.title': 'Become a Nexora Host',
    'share.space': 'Share your space and earn extra income while helping travelers discover authentic Balkan experiences',
    'list.space': 'List Your Space',
    'list.space.desc': 'Whether you have a spare room, entire apartment, or unique property, you can list it on Nexora. Our platform makes it easy to showcase your space to travelers.',
    'set.price': 'Set Your Price',
    'set.price.desc': 'You control your pricing and availability. Our dynamic pricing tools help you maximize your earnings while staying competitive in the market.',
    'welcome.guests': 'Welcome Guests',
    'welcome.guests.desc': 'Connect with travelers from around the world. Share local insights and create memorable experiences that showcase the best of Balkan hospitality.',
    'protected.supported': 'Protected & Supported',
    'protected.supported.desc': 'Our host protection program covers your property, and our support team is available 24/7 to help you succeed as a host.',
    'ready.start': 'Ready to Get Started?',
    'ready.start.desc': 'Join thousands of hosts across the Balkans who are earning extra income and sharing their spaces with travelers.',
    'browse.properties': 'Browse Properties',
    // Add Property Form
    'add.property': 'Add Your Property',
    'add.property.desc': 'Fill out the form below to list your property on Nexora',
    'property.title': 'Property Title',
    'property.title.placeholder': 'e.g., Beautiful Apartment in City Center',
    'property.location': 'Location',
    'property.location.placeholder': 'e.g., Belgrade, Serbia',
    'property.location.picker': 'Choose location (optional)',
    'property.location.hint': 'Pick a location above or type your own (e.g. city, country)',
    'property.location.map.hint': 'Click on the map exactly where your property is. You can also enter the location name below.',
    'property.location.name': 'Location name or address',
    'location.map': 'Map Location',
    'property.description': 'Description',
    'property.description.placeholder': 'Describe your property...',
    'property.price': 'Price per Night (BAM)',
    'property.guests': 'Number of Guests',
    'property.bedrooms': 'Bedrooms',
    'property.beds': 'Beds',
    'property.bathrooms': 'Bathrooms',
    'property.image.url': 'Main Image URL',
    'property.image.url.placeholder': 'https://example.com/image.jpg',
    'property.images': 'Additional Image URLs (one per line)',
    'property.images.placeholder': 'https://example.com/image1.jpg\nhttps://example.com/image2.jpg',
    'property.amenities': 'Amenities (comma separated)',
    'property.amenities.placeholder': 'WiFi, Kitchen, Parking, TV',
    'property.category': 'Category (comma separated)',
    'property.category.placeholder': 'City, Historic, Mansions',
    'property.host.name': 'Host Name',
    'property.host.name.placeholder': 'Your name',
    'property.host.avatar': 'Host Avatar URL (optional)',
    'property.check.in': 'Check-in Time',
    'property.check.out': 'Check-out Time',
    'property.submit': 'Submit Property',
    'property.submitting': 'Submitting...',
    'listing.added': 'Listing added successfully!',
    'listing.failed': 'Something went wrong. Please try again.',
    'listing.saved.local': 'Saved locally. Add VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY to .env to save permanently.',
    'property.success': 'Property added successfully!',
    'property.success.desc': 'Your property has been listed and is now visible to travelers.',
    'property.view': 'View Your Property',
    'property.add.another': 'Add Another Property',
    'property.edit': 'Edit',
    'property.edit.title': 'Edit your listing',
    'property.edit.desc': 'Update details of your property.',
    'property.edit.form': 'Edit listing',
    'property.save.changes': 'Save changes',
    'property.updated': 'Changes saved!',
    'property.delete': 'Delete',
    'property.delete.confirm': 'Are you sure you want to delete this listing? This cannot be undone.',
    'property.deleted': 'Listing deleted.',
    'required.field': 'This field is required',
    'invalid.url': 'Please enter a valid URL',
    'invalid.number': 'Please enter a valid number',
    'invalid.price': 'Price must be greater than 0',
    'invalid.numbers': 'Guests must be at least 1. Bedrooms, beds and bathrooms cannot be negative.',
    'description.too.long': 'Description cannot exceed 2000 characters',
    'title.too.long': 'Title cannot exceed 200 characters',
    // How It Works
    'how.works.title': 'How Nexora Works',
    'discover.steps': 'Discover amazing stays across the Balkans in three simple steps',
    'search.step': '1. Search',
    'search.step.desc': 'Browse through our curated collection of authentic Balkan properties. Use filters to find the perfect location, price range, and amenities that match your travel style.',
    'book.step': '2. Book',
    'book.step.desc': 'Select your dates and number of guests. Our dynamic pricing ensures you get the best rate. Complete your reservation securely with instant confirmation.',
    'stay.step': '3. Stay',
    'stay.step.desc': 'Enjoy your authentic Balkan experience! Our hosts are committed to providing you with local insights and ensuring your stay is memorable.',
    'review.step': '4. Review',
    'review.step.desc': 'Share your experience and help future travelers discover the best Balkan stays. Your feedback helps us maintain high standards.',
    'start.search': 'Start Your Search',
    'language.english': 'English',
    'language.serbian': 'Srpski',
    // FAQ
    'faq.cancel': 'How do I cancel my reservation?',
    'faq.cancel.answer': "You can cancel your reservation from your account dashboard. Cancellation policies vary by property and are clearly displayed before booking. Most properties offer free cancellation up to 48 hours before check-in.",
    'faq.payment': 'What payment methods do you accept?',
    'faq.payment.answer': 'We accept all major credit cards (Visa, Mastercard, American Express) and debit cards. Payment is processed securely at the time of booking.',
    'faq.contact.host': 'How do I contact my host?',
    'faq.contact.host.answer': "Once your booking is confirmed, you'll receive contact information for your host. You can also message them directly through the Nexora platform.",
    'faq.problem': 'What if I have a problem during my stay?',
    'faq.problem.answer': "Contact your host immediately through the platform. If the issue isn't resolved, reach out to our 24/7 support team. We're here to help ensure your stay is comfortable.",
    'faq.pets': 'Are pets allowed?',
    'faq.pets.answer': 'Pet policies vary by property. Check the property listing for specific pet policies, or contact the host directly to discuss your needs.',
    'faq.refund': 'What is your refund policy?',
    'faq.refund.answer': 'Refund policies depend on the cancellation policy of your specific booking. Check your booking confirmation for details, or contact support for assistance.',
    // Privacy Policy Details
    'privacy.matters': 'Your Privacy Matters',
    'privacy.intro': 'At Nexora, we are committed to protecting your privacy and ensuring the security of your personal information. This Privacy Policy explains how we collect, use, and safeguard your data when you use our platform.',
    'info.collect': 'Information We Collect',
    'info.collect.intro': 'We collect information that you provide directly to us, including:',
    'info.collect.account': 'Account information (name, email, phone number)',
    'info.collect.payment': 'Payment information (processed securely through third-party providers)',
    'info.collect.booking': 'Booking details and travel preferences',
    'info.collect.communications': 'Communications with hosts and our support team',
    'how.use': 'How We Use Your Information',
    'how.use.intro': 'We use your information to:',
    'how.use.process': 'Process and manage your bookings',
    'how.use.communicate': 'Communicate with you about your reservations',
    'how.use.improve': 'Improve our services and user experience',
    'how.use.offers': 'Send you relevant travel offers (with your consent)',
    'how.use.security': 'Ensure platform security and prevent fraud',
    'data.security': 'Data Security',
    'data.security.desc': 'We implement industry-standard security measures to protect your personal information. All data is encrypted in transit and at rest. We never share your information with third parties except as necessary to provide our services or as required by law.',
    'your.rights': 'Your Rights',
    'your.rights.intro': 'You have the right to:',
    'rights.access': 'Access your personal data',
    'rights.correct': 'Correct inaccurate information',
    'rights.delete': 'Request deletion of your data',
    'rights.optout': 'Opt-out of marketing communications',
    'rights.portability': 'Data portability',
    'privacy.contact': 'Contact Us',
    'privacy.contact.desc': 'If you have questions about this Privacy Policy or wish to exercise your rights, please contact us at',
    // Terms of Service Details
    'terms.agreement': 'Agreement to Terms',
    'terms.agreement.desc': 'By accessing and using Nexora, you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you may not use our platform.',
    'terms.user.responsibilities': 'User Responsibilities',
    'terms.user.intro': 'As a user of Nexora, you agree to:',
    'user.accurate': 'Provide accurate and complete information',
    'user.lawful': 'Use the platform only for lawful purposes',
    'user.respect': 'Respect the property and rights of hosts',
    'user.comply': 'Comply with all applicable laws and regulations',
    'user.security': 'Maintain the security of your account',
    'terms.booking': 'Booking Terms',
    'terms.booking.intro': 'When making a booking:',
    'booking.contract': 'You are entering into a contract directly with the host',
    'booking.payment': 'Payment is processed at the time of booking',
    'booking.cancellation': 'Cancellation policies vary by property and are clearly displayed',
    'booking.damages': 'You are responsible for any damages to the property',
    'booking.refunds': 'Refunds are subject to the host\'s cancellation policy',
    'terms.host.responsibilities': 'Host Responsibilities',
    'terms.host.intro': 'Hosts agree to:',
    'host.accurate': 'Provide accurate property descriptions and photos',
    'host.maintain': 'Maintain properties in safe and habitable condition',
    'host.honor': 'Honor confirmed reservations',
    'host.respond': 'Respond promptly to guest inquiries',
    'host.comply': 'Comply with all local laws and regulations',
    'terms.liability': 'Limitation of Liability',
    'terms.liability.desc': 'Nexora acts as a platform connecting guests and hosts. We are not responsible for the condition of properties, the conduct of hosts or guests, or any disputes that may arise. Our liability is limited to the service fees we collect.',
    'terms.modifications': 'Modifications',
    'terms.modifications.desc': 'We reserve the right to modify these terms at any time. Continued use of the platform after changes constitutes acceptance of the new terms.',
    'booking.confirmation': 'Booking Confirmation',
    'confirming.booking': 'Confirming your booking...',
    'please.wait': 'Please wait.',
    'view.bookings': 'View My Bookings',
    'invalid.session': 'Invalid session',
    'inbox': 'Inbox',
    'unread.message': 'unread message',
    'unread.messages': 'unread messages',
    'contact.host': 'Contact host',
    'contact.only.supabase': 'Messaging is available for listed properties only.',
    'no.messages': 'No messages yet',
    'no.messages.desc': 'Contact a host from a property page to start a conversation.',
    'type.message': 'Type a message...',
    'select.conversation': 'Select a conversation',
    'forgot.password': 'Forgot password?',
    'reset.instructions': 'Enter your email and we\'ll send you a link to reset your password.',
    'reset.send': 'Send reset link',
    'reset.check.email': 'Check your email for the reset link.',
    'reset.check.email.detail': 'If an account exists for that email, you will receive a link to reset your password.',
    'reset.failed': 'Failed to send reset email.',
    'reset.email.sent': 'Reset link sent! Check your email.',
    'reset.password': 'Set New Password',
    'reset.new.password.instructions': 'Enter your new password below.',
    'reset.update.password': 'Update password',
    'password.updated': 'Password updated successfully!',
    'property.image.required': 'Please add at least one image.',
    'check.email.verify': 'Check your email to verify your account.',
    'cancellation.policy': 'Cancellation policy',
    'cancellation.flexible': 'Free cancellation up to 24 hours before check-in.',
    'cancellation.moderate': 'Free cancellation up to 5 days before check-in. 50% refund if cancelled within 5 days.',
    'cancellation.strict': '50% refund up to 7 days before check-in. No refund within 7 days of check-in.',
    'cookie.consent': 'Cookie consent',
    'cookie.message': 'We use cookies to improve your experience. By continuing, you accept our ',
    'cookie.and': 'and',
    'cookie.accept': 'Accept',
  },
  sr: {
    'explore.all': 'Istraži sve',
    'stays': 'smještaja',
    'stay': 'smještaj',
    'search.results': 'Rezultati pretrage za',
    'properties': 'Nekretnine',
    'no.properties': 'Nekretnine nisu pronađene',
    'try.adjusting': 'Pokušajte da prilagodite kriterijume pretrage',
    'find.adventure': 'Pronađite svoju sledeću avanturu',
    'discover.places': 'Otkrijte jedinstvena mesta za boravak širom Balkana',
    'become.host': 'Postanite domaćin',
    'my.bookings': 'Moje rezervacije',
    'no.bookings': 'Još nema rezervacija',
    'no.bookings.desc': 'Počnite da istražujete i rezervišite prvi smeštaj!',
    'no.bookings.found': 'Nema pronađenih rezervacija',
    'explore.properties': 'Pregledaj nekretnine',
    'search.bookings': 'Pretraži rezervacije',
    'bookings.all': 'Sve',
    'bookings.upcoming': 'Nadolazeće',
    'bookings.completed': 'Završeno',
    'bookings.cancelled': 'Otkazano',
    'booking.status.upcoming': 'Nadolazeće',
    'booking.status.completed': 'Završeno',
    'booking.status.cancelled': 'Otkazano',
    'cancel.booking.confirm': 'Da li ste sigurni da želite da otkažete ovu rezervaciju?',
    'booking.cancelled': 'Rezervacija otkazana',
    'cancel': 'Otkaži',
    'cancel.booking': 'Otkaži rezervaciju',
    'view.property': 'Pogledaj nekretninu',
    'saved.properties': 'Sačuvane nekretnine',
    'saved.property': 'sačuvana nekretnina',
    'profile': 'Profil',
    'welcome': 'Dobrodošli',
    'member.since': 'Član od',
    'total.spent': 'Ukupno potrošeno',
    'quick.actions': 'Brze akcije',
    'list.your.place': 'Objavi svoje mesto',
    'find.stays': 'Pronađi smeštaj',
    'favorite.destinations': 'Omiljene destinacije',
    'saved': 'sačuvano',
    'active': 'aktivno',
    'explore': 'Istraži',
    'select.language': 'Izaberi jezik',
    'light': 'Svetlo',
    'dark': 'Tamno',
    'language': 'Jezik',
    'theme': 'Tema',
    'no.favorites': 'Još nema omiljenih',
    'no.favorites.desc': 'Počnite da istražujete i sačuvajte svoje omiljene nekretnine!',
    'removed.from.favorites': 'Uklonjeno iz omiljenih',
    'remove.from.favorites': 'Ukloni iz omiljenih',
    'added.to.favorites': 'Dodato u omiljene',
    'recent.views': 'Nedavno pregledano',
    'clear.recent.views': 'Obriši nedavno pregledano',
    'host.dashboard': 'Kontrolna tabla domaćina',
    'settings': 'Podešavanja',
    'log.out': 'Odjavi se',
    'account': 'Nalog',
    'edit.profile': 'Edit Profil',
    'display.name': 'Display Name',
    'save': 'Sačuvaj',
    'your.name': 'Vaše ime',
    'saving': 'Čuvanje...',
    'profile.updated': 'Profil ažuriran',
    'log.in': 'Prijavi se',
    'sign.up': 'Registruj se',
    'sign.in': 'Prijavi se',
    'register': 'Registracija',
    'email.address': 'Email adresa',
    'password': 'Lozinka',
    'full.name': 'Ime i prezime',
    'login.title': 'Prijavite se na nalog',
    'login.subtitle': 'Dobrodošli nazad',
    'register.title': 'Kreirajte nalog',
    'register.subtitle': 'Pridružite se Nexori za rezervacije i objave',
    'no.account': 'Nemate nalog?',
    'have.account': 'Već imate nalog?',
    'login.failed': 'Pogrešan email ili lozinka',
    'register.failed': 'Registracija nije uspela. Pokušajte ponovo.',
    'register.success': 'Nalog je uspešno kreiran',
    'login.required': 'Prijavite se da biste nastavili',
    'my.listings': 'Moji smeštaji',
    'host.reservations': 'Rezervacije',
    'host.reservations.short': 'Rezervacije tvojih smeštaja',
    'host.reservations.desc': 'Pregled rezervacija za tvoje objavljene smeštaje.',
    'host.no.reservations': 'Nema rezervacija',
    'host.no.reservations.desc': 'Kada neko rezerviše tvoj smeštaj, ovde će se pojaviti.',
    'host.guest': 'Gost',
    'host.booked': 'rezervisao',
    'add.property.requires.login': 'Prijavite se da dodate smeštaj',
    'reserve.requires.login': 'Prijavite se da rezervišete',
    'delete.account': 'Obriši nalog',
    'delete.account.desc': 'Trajno obrišite nalog i sve povezane podatke. Ovo se ne može poništiti.',
    'delete.account.confirm': 'Jeste li sigurni? Upišite "DELETE" za potvrdu.',
    'delete.account.done': 'Nalog je obrisan. Odjavljeni ste.',
    'night': 'noć',
    'anywhere': 'Bilo gde',
    'any.week': 'Bilo koja nedelja',
    'add.guests': 'Dodaj goste',
    'search': 'Pretraži',
    'search.destinations': 'Pretraži destinacije...',
    // Categories
    'all': 'Sve',
    'mansions': 'Vile',
    'cabins': 'Kolibe',
    'beach': 'Plaža',
    'mountains': 'Planine',
    'city': 'Grad',
    'lofts': 'Loftovi',
    'countryside': 'Selo',
    'camping': 'Kamping',
    // Filters
    'filters': 'Filteri',
    'reset': 'Resetuj',
    'sort.by': 'Sortiraj po',
    'most.popular': 'Najpopularnije',
    'highest.rated': 'Najbolje ocenjeno',
    'price.low.high': 'Cena: Od najniže',
    'price.high.low': 'Cena: Od najviše',
    'price.per.night': 'Cena po noći',
    'bedrooms': 'Spavaće sobe',
    'beds': 'Kreveti',
    'bathrooms': 'Kupatila',
    'guests': 'Gosti',
    'amenities': 'Sadržaji',
    'any': 'Bilo koje',
    'guest': 'gost',
    'guests.plural': 'gostiju',
    // Property Detail
    'back': 'Nazad',
    'reviews': 'recenzija',
    'no.reviews.yet': 'Još nema recenzija',
    'leave.review': 'Ostavi recenziju',
    'login.to.review': 'Prijavi se da ostaviš recenziju',
    'submit.review': 'Pošalji recenziju',
    'your.rating': 'Tvoja ocena',
    'your.review': 'Tvoja recenzija',
    'review.submitted': 'Recenzija poslata',
    'review.failed': 'Slanje recenzije nije uspelo',
    'already.reviewed': 'Već si ostavio/la recenziju za ovu nekretninu',
    'hosted.by': 'Domaćin',
    'superhost': 'Superdomaćin',
    'responds': 'Odgovara',
    'response.rate': 'stopa odgovora',
    'what.place.offers': 'Šta ovo mesto nudi',
    'check.in.out': 'Prijava i odjava',
    'check.in': 'Prijava',
    'check.out': 'Odjava',
    'check.in.date': 'Datum prijave',
    'check.out.date': 'Datum odjave',
    'add.dates': 'Dodaj datume',
    'reserve': 'Rezerviši',
    'reserving': 'Rezervisanje...',
    'reservation.successful': 'Rezervacija uspešna!',
    'reservation.failed': 'Rezervacija nije uspela. Molimo pokušajte ponovo.',
    'dates.unavailable': 'Izabrani datumi više nisu dostupni.',
    'select.dates.first': 'Molimo prvo izaberite datume prijave i odjave',
    'check.email': 'Proverite email za potvrdu.',
    'total': 'Ukupno',
    'cleaning.fee': 'Trošak čišćenja',
    'service.fee': 'Trošak usluge',
    'copy.link': 'Kopiraj link',
    'link.copied': 'Link je kopiran!',
    'share.facebook': 'Podeli na Facebooku',
    'share.twitter': 'Podeli na Twitteru',
    'show.all.photos': 'Prikaži sve fotografije',
    'image.unavailable': 'Slika nije dostupna',
    'property.not.found': 'Nekretnina nije pronađena',
    'property.not.exist': 'Nekretnina koju tražite ne postoji.',
    'go.home': 'Idi na početnu',
    'page.not.found': 'Stranica nije pronađena',
    'page.not.found.desc': 'Stranica koju tražite ne postoji ili je premeštena.',
    'something.wrong': 'Nešto je pošlo po zlu',
    'try.again': 'Molimo pokušajte ponovo kasnije.',
    'back.to.home': 'Nazad na početnu',
    // Privacy Policy
    'privacy.policy.title': 'Politika privatnosti',
    'last.updated': 'Poslednje ažuriranje: Januar 2025',
    // Terms of Service
    'terms.of.service.title': 'Uslovi korišćenja',
    // Booking Calendar
    'adult': 'odrasla osoba',
    'adults': 'odraslih osoba',
    'child': 'dete',
    'children': 'dece',
    'approximate.prices': 'Približne cene u BAM za boravak od 1 noć',
    'base': 'Osnovna',
    'nights': 'noći',
    'months.ago': 'meseci',
    // Footer
    'support': 'Podrška',
    'help.center': 'Centar za pomoć',
    'safety.information': 'Informacije o bezbednosti',
    'cancellation.options': 'Opcije otkazivanja',
    'contact.us': 'Kontaktirajte nas',
    'hosting': 'Domaćinstvo',
    'host.resources': 'Resursi za domaćine',
    'community.forum': 'Forum zajednice',
    'hosting.responsibly': 'Odgovorno domaćinstvo',
    'about': 'O projektu',
    'about.builtBy': 'Projekat napravio/la',
    'footer.builtBy': 'Napravio/la',
    'how.it.works': 'Kako funkcioniše',
    'newsroom': 'Vesti',
    'careers': 'Karijere',
    'investors': 'Investitori',
    'legal': 'Pravno',
    'privacy.policy': 'Politika privatnosti',
    'terms.of.service': 'Uslovi korišćenja',
    'all.rights.reserved': 'Sva prava zadržana',
    // Help Center
    'help.center.title': 'Centar za pomoć',
    'find.answers': 'Pronađite odgovore na česta pitanja',
    'search.for.help': 'Pretraži pomoć...',
    'frequently.asked': 'Često postavljana pitanja',
    'no.results': 'Nema rezultata. Pokušajte sa drugim pojmom.',
    'assistant.title': 'Nexora asistent',
    'assistant.subtitle': 'Pitajte o platformi i smeštaju na Balkanu.',
    'assistant.placeholder': 'Pitanje o Nexori, rezervacijama, pomoći...',
    'assistant.welcome': 'Pitajte bilo šta o Nexori, rezervacijama ili smeštaju na Balkanu.',
    'assistant.error': 'Nisam mogao da odgovorim. Pokušajte ponovo ili koristite Help / Kontakt.',
    'still.need.help': 'Još uvek trebate pomoć?',
    'support.available': 'Naš tim za podršku je dostupan 24/7 da vam pomogne.',
    'contact.support': 'Kontaktirajte podršku',
    // Contact
    'contact.us.title': 'Kontaktirajte nas',
    'here.to.help': 'Tu smo da pomognemo! Kontaktirajte naš tim.',
    'email': 'Email',
    'phone': 'Telefon',
    'office': 'Kancelarija',
    'support.hours': 'Radno vreme podrške',
    'support.hours.note': 'Podrška radnim danima.',
    'send.message': 'Pošaljite nam poruku',
    'name': 'Ime',
    'subject': 'Predmet',
    'message': 'Poruka',
    'send': 'Pošalji poruku',
    'message.sent': 'Poruka je uspešno poslata!',
    'contact.success': 'Poruka poslata. Javićemo vam se.',
    'contact.error': 'Slanje nije uspelo. Pokušajte ponovo.',
    'contact.demo.note': 'Portfolio demo. Poruke se čuvaju u Supabase. Koristite formu za kontakt.',
    'contact.via.form': 'Putem kontakt forme',
    'contact.region': 'Balkan',
    'get.back': 'Odgovorićemo vam u roku od 24 sata.',
    // Become Host
    'become.host.title': 'Postanite domaćin',
    'share.space': 'Podelite svoj prostor i zaradite dodatni prihod',
    // How It Works
    'how.works.title': 'Kako Nexora funkcioniše',
    'discover.steps': 'Otkrijte neverovatne smještaje širom Balkana u tri jednostavna koraka',
    'search.step': '1. Pretraži',
    'search.step.desc': 'Pregledajte našu kuririsanu kolekciju autentičnih balkanskih nekretnina. Koristite filtere da pronađete savršenu lokaciju, cenovni rang i sadržaje koji odgovaraju vašem stilu putovanja.',
    'book.step': '2. Rezerviši',
    'book.step.desc': 'Izaberite datume i broj gostiju. Naše dinamičko određivanje cena osigurava da dobijete najbolju cenu. Završite rezervaciju sigurno sa trenutnom potvrdom.',
    'stay.step': '3. Ostani',
    'stay.step.desc': 'Uživajte u svom autentičnom balkanskom iskustvu! Naši domaćini su posvećeni pružanju lokalnih uvida i osiguravanju da vaš boravak bude nezaboravan.',
    'review.step': '4. Oceni',
    'review.step.desc': 'Podelite svoje iskustvo i pomozite budućim putnicima da otkriju najbolje balkanske smještaje. Vaše povratne informacije pomažu nam da održimo visoke standarde.',
    'start.search': 'Započni pretragu',
    'language.english': 'English',
    'language.serbian': 'Srpski',
    // Become Host
    'list.space': 'Objavi svoj prostor',
    'list.space.desc': 'Bilo da imate slobodnu sobu, ceo stan ili jedinstvenu nekretninu, možete je objaviti na Nexori. Naša platforma olakšava predstavljanje vašeg prostora putnicima.',
    'set.price': 'Postavi cenu',
    'set.price.desc': 'Vi kontrolišete cene i dostupnost. Naši alati za dinamičko određivanje cena pomažu vam da povećate zaradu i ostanete konkurentni na tržištu.',
    'welcome.guests': 'Dobrodošli gosti',
    'welcome.guests.desc': 'Povežite se sa putnicima iz celog sveta. Podelite lokalne savete i stvorite nezaboravna iskustva koja predstavljaju najbolje balkansko gostoprimstvo.',
    'protected.supported': 'Zaštićeno i podržano',
    'protected.supported.desc': 'Program za zaštitu domaćina pokriva vašu nekretninu, a naš tim za podršku dostupan je 24/7 da vam pomogne da uspete kao domaćin.',
    'ready.start': 'Spremni da počnete?',
    'ready.start.desc': 'Pridružite se hiljadama domaćina širom Balkana koji zarađuju dodatni prihod i dele svoje prostore sa putnicima.',
    'browse.properties': 'Pregledaj nekretnine',
    // Add Property Form
    'add.property': 'Dodaj svoju nekretninu',
    'add.property.desc': 'Popunite formu ispod da biste objavili svoju nekretninu na Nexora',
    'property.title': 'Naziv nekretnine',
    'property.title.placeholder': 'npr., Lep stan u centru grada',
    'property.location': 'Lokacija',
    'property.location.placeholder': 'npr., Beograd, Srbija',
    'property.location.picker': 'Izaberi lokaciju (opciono)',
    'property.location.hint': 'Izaberite lokaciju iz liste ili upišite svoju (npr. grad, država)',
    'property.location.map.hint': 'Kliknite na mapu tačno gde se nalazi smeštaj. Možete uneti i naziv lokacije ispod.',
    'property.location.name': 'Naziv lokacije ili adresa',
    'location.map': 'Lokacija na mapi',
    'property.description': 'Opis',
    'property.description.placeholder': 'Opišite svoju nekretninu...',
    'property.price': 'Cena po noći (BAM)',
    'property.guests': 'Broj gostiju',
    'property.bedrooms': 'Spavaće sobe',
    'property.beds': 'Kreveti',
    'property.bathrooms': 'Kupatila',
    'property.image.url': 'URL glavne slike',
    'property.image.url.placeholder': 'https://example.com/slika.jpg',
    'property.images': 'URL dodatnih slika (jedna po liniji)',
    'property.images.placeholder': 'https://example.com/slika1.jpg\nhttps://example.com/slika2.jpg',
    'property.amenities': 'Sadržaji (odvojeno zarezom)',
    'property.amenities.placeholder': 'WiFi, Kuhinja, Parking, TV',
    'property.category': 'Kategorija (odvojeno zarezom)',
    'property.category.placeholder': 'Grad, Istorijski, Vile',
    'property.host.name': 'Ime domaćina',
    'property.host.name.placeholder': 'Vaše ime',
    'property.host.avatar': 'URL avatara domaćina (opciono)',
    'property.check.in': 'Vreme prijave',
    'property.check.out': 'Vreme odjave',
    'property.submit': 'Pošalji nekretninu',
    'property.submitting': 'Slanje...',
    'listing.added': 'Nekretnina je uspešno dodata!',
    'listing.failed': 'Nešto nije u redu. Pokušajte ponovo.',
    'listing.saved.local': 'Sačuvano samo lokalno. Dodajte VITE_SUPABASE_URL i VITE_SUPABASE_PUBLISHABLE_KEY u .env da bi se trajno čuvalo.',
    'property.success': 'Nekretnina je uspešno dodata!',
    'property.success.desc': 'Vaša nekretnina je objavljena i sada je vidljiva putnicima.',
    'property.view': 'Pogledaj svoju nekretninu',
    'property.add.another': 'Dodaj još jednu nekretninu',
    'property.edit': 'Izmeni',
    'property.edit.title': 'Izmeni svoj smeštaj',
    'property.edit.desc': 'Ažuriraj podatke o svojoj nekretnini.',
    'property.edit.form': 'Izmena oglasa',
    'property.save.changes': 'Sačuvaj izmene',
    'property.updated': 'Izmene sačuvane!',
    'property.delete': 'Obriši',
    'property.delete.confirm': 'Da li ste sigurni da želite da obrišete ovaj oglas? Ovo se ne može poništiti.',
    'property.deleted': 'Oglas je obrisan.',
    'required.field': 'Ovo polje je obavezno',
    'invalid.url': 'Molimo unesite validan URL',
    'invalid.number': 'Molimo unesite validan broj',
    'invalid.price': 'Cena mora biti veća od 0',
    'invalid.numbers': 'Broj gostiju mora biti najmanje 1. Sobe, kreveti i kupatila ne mogu biti negativni.',
    'description.too.long': 'Opis ne sme preći 2000 karaktera',
    'title.too.long': 'Naslov ne sme preći 200 karaktera',
    // FAQ
    'faq.cancel': 'Kako mogu da otkažem rezervaciju?',
    'faq.cancel.answer': 'Možete otkazati rezervaciju sa kontrolne table vašeg naloga. Politika otkazivanja varira po nekretnini i jasno je prikazana pre rezervacije. Većina nekretnina nudi besplatno otkazivanje do 48 sati pre prijave.',
    'faq.payment': 'Koje načine plaćanja prihvatate?',
    'faq.payment.answer': 'Prihvatamo sve glavne kreditne kartice (Visa, Mastercard, American Express) i debitne kartice. Plaćanje se obrađuje sigurno u trenutku rezervacije.',
    'faq.contact.host': 'Kako mogu da kontaktiran domaćina?',
    'faq.contact.host.answer': 'Nakon što je vaša rezervacija potvrđena, dobićete kontakt informacije za vašeg domaćina. Takođe možete da im pišete direktno preko Nexora platforme.',
    'faq.problem': 'Šta ako imam problem tokom boravka?',
    'faq.problem.answer': 'Kontaktirajte svog domaćina odmah preko platforme. Ako problem nije rešen, obratite se našem timu za podršku 24/7. Tu smo da pomognemo da vaš boravak bude udoban.',
    'faq.pets': 'Da li su kućni ljubimci dozvoljeni?',
    'faq.pets.answer': 'Politika za kućne ljubimce varira po nekretnini. Proverite oglas nekretnine za specifične politike za kućne ljubimce, ili kontaktirajte domaćina direktno da razgovarate o vašim potrebama.',
    'faq.refund': 'Koja je vaša politika povraćaja novca?',
    'faq.refund.answer': 'Politika povraćaja novca zavisi od politike otkazivanja vaše specifične rezervacije. Proverite potvrdu rezervacije za detalje, ili kontaktirajte podršku za pomoć.',
    // Privacy Policy Details
    'privacy.matters': 'Vaša privatnost je važna',
    'privacy.intro': 'U Nexora, posvećeni smo zaštiti vaše privatnosti i osiguravanju bezbednosti vaših ličnih podataka. Ova Politika privatnosti objašnjava kako prikupljamo, koristimo i štitimo vaše podatke kada koristite našu platformu.',
    'info.collect': 'Informacije koje prikupljamo',
    'info.collect.intro': 'Prikupljamo informacije koje nam direktno pružate, uključujući:',
    'info.collect.account': 'Informacije o nalogu (ime, email, broj telefona)',
    'info.collect.payment': 'Informacije o plaćanju (obrađuju se sigurno preko trećih strana)',
    'info.collect.booking': 'Detalji rezervacije i preferencije putovanja',
    'info.collect.communications': 'Komunikacije sa domaćinima i našim timom za podršku',
    'how.use': 'Kako koristimo vaše informacije',
    'how.use.intro': 'Koristimo vaše informacije za:',
    'how.use.process': 'Obradu i upravljanje vašim rezervacijama',
    'how.use.communicate': 'Komunikaciju sa vama o vašim rezervacijama',
    'how.use.improve': 'Poboljšanje naših usluga i korisničkog iskustva',
    'how.use.offers': 'Slanje relevantnih ponuda za putovanja (uz vašu saglasnost)',
    'how.use.security': 'Osiguravanje bezbednosti platforme i sprečavanje prevara',
    'data.security': 'Bezbednost podataka',
    'data.security.desc': 'Primenjujemo standardne mere bezbednosti industrije za zaštitu vaših ličnih podataka. Svi podaci su šifrovani u tranzitu i u mirovanju. Nikada ne delimo vaše informacije sa trećim stranama osim što je neophodno za pružanje naših usluga ili kako zahteva zakon.',
    'your.rights': 'Vaša prava',
    'your.rights.intro': 'Imate pravo da:',
    'rights.access': 'Pristupite svojim ličnim podacima',
    'rights.correct': 'Ispravite netačne informacije',
    'rights.delete': 'Zatražite brisanje vaših podataka',
    'rights.optout': 'Odustanete od marketinških komunikacija',
    'rights.portability': 'Prenos podataka',
    'privacy.contact': 'Kontaktirajte nas',
    'privacy.contact.desc': 'Ako imate pitanja o ovoj Politici privatnosti ili želite da iskoristite svoja prava, molimo kontaktirajte nas na',
    // Terms of Service Details
    'terms.agreement': 'Saglasnost sa uslovima',
    'terms.agreement.desc': 'Pristupanjem i korišćenjem Nexora, slažete se da ste vezani ovim Uslovima korišćenja. Ako se ne slažete sa bilo kojim delom ovih uslova, ne smete koristiti našu platformu.',
    'terms.user.responsibilities': 'Odgovornosti korisnika',
    'terms.user.intro': 'Kao korisnik Nexora, slažete se da:',
    'user.accurate': 'Pružate tačne i potpune informacije',
    'user.lawful': 'Koristite platformu samo u zakonite svrhe',
    'user.respect': 'Poštujete imovinu i prava domaćina',
    'user.comply': 'Pridržavate se svih primenjivih zakona i propisa',
    'user.security': 'Održavate bezbednost svog naloga',
    'terms.booking': 'Uslovi rezervacije',
    'terms.booking.intro': 'Prilikom rezervacije:',
    'booking.contract': 'Ulazite u ugovor direktno sa domaćinom',
    'booking.payment': 'Plaćanje se obrađuje u trenutku rezervacije',
    'booking.cancellation': 'Politika otkazivanja varira po nekretnini i jasno je prikazana',
    'booking.damages': 'Odgovorni ste za bilo kakvu štetu na nekretnini',
    'booking.refunds': 'Povraćaj novca zavisi od politike otkazivanja domaćina',
    'terms.host.responsibilities': 'Odgovornosti domaćina',
    'terms.host.intro': 'Domaćini se slažu da:',
    'host.accurate': 'Pružaju tačne opise nekretnina i fotografije',
    'host.maintain': 'Održavaju nekretnine u bezbednom i pogodnom stanju',
    'host.honor': 'Poštuju potvrđene rezervacije',
    'host.respond': 'Brzo odgovaraju na upite gostiju',
    'host.comply': 'Pridržavaju se svih lokalnih zakona i propisa',
    'terms.liability': 'Ograničenje odgovornosti',
    'terms.liability.desc': 'Nexora deluje kao platforma koja povezuje goste i domaćine. Nismo odgovorni za stanje nekretnina, ponašanje domaćina ili gostiju, ili bilo kakve sporove koji mogu nastati. Naša odgovornost je ograničena na naknade za usluge koje prikupljamo.',
    'terms.modifications': 'Izmene',
    'terms.modifications.desc': 'Zadržavamo pravo da ove uslove izmenimo u bilo kom trenutku. Nastavak korišćenja platforme nakon izmena predstavlja prihvatanje novih uslova.',
    'booking.confirmation': 'Potvrda rezervacije',
    'confirming.booking': 'Potvrđujemo vašu rezervaciju...',
    'please.wait': 'Molimo sačekajte.',
    'view.bookings': 'Pogledaj moje rezervacije',
    'invalid.session': 'Nevažeća sesija',
    'inbox': 'Sanduče',
    'unread.message': 'nepročitana poruka',
    'unread.messages': 'nepročitanih poruka',
    'contact.host': 'Kontaktiraj hosta',
    'contact.only.supabase': 'Poruke su dostupne samo za objavljene nekretnine.',
    'no.messages': 'Još nema poruka',
    'no.messages.desc': 'Kontaktirajte hosta sa stranice nekretnine da započnete razgovor.',
    'type.message': 'Napišite poruku...',
    'select.conversation': 'Izaberite razgovor',
    'forgot.password': 'Zaboravljena lozinka?',
    'reset.instructions': 'Unesite email i poslaćemo vam link za resetovanje lozinke.',
    'reset.send': 'Pošalji link',
    'reset.check.email': 'Proverite email za link za resetovanje.',
    'reset.check.email.detail': 'Ako postoji nalog za taj email, dobićete link za resetovanje lozinke.',
    'reset.failed': 'Slanje emaila nije uspelo.',
    'reset.email.sent': 'Link poslat! Proverite email.',
    'reset.password': 'Nova lozinka',
    'reset.new.password.instructions': 'Unesite novu lozinku ispod.',
    'reset.update.password': 'Ažuriraj lozinku',
    'password.updated': 'Lozinka je uspešno ažurirana!',
    'property.image.required': 'Molimo dodajte bar jednu sliku.',
    'check.email.verify': 'Proverite email da potvrdite nalog.',
    'cancellation.policy': 'Politika otkazivanja',
    'cancellation.flexible': 'Besplatno otkazivanje do 24h pre prijave.',
    'cancellation.moderate': 'Besplatno otkazivanje do 5 dana pre prijave. 50% povrata ako otkažete u roku od 5 dana.',
    'cancellation.strict': '50% povrata do 7 dana pre prijave. Bez povrata u roku od 7 dana.',
    'cookie.consent': 'Saglasnost za kolačiće',
    'cookie.message': 'Koristimo kolačiće da poboljšamo vaše iskustvo. Nastavkom prihvatate našu ',
    'cookie.and': 'i',
    'cookie.accept': 'Prihvati',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  // Sync with other tabs
  useEffect(() => {
    const handleStorageChange = (e: StorageEvent) => {
      if (e.key === 'language' && e.newValue) {
        setLanguageState(e.newValue as Language);
      }
    };

    window.addEventListener('storage', handleStorageChange);
    return () => window.removeEventListener('storage', handleStorageChange);
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string, fallback?: string): string => {
    const langMap = translations[language];
    const value = langMap ? langMap[key] : undefined;
    if (value) return value;
    return fallback !== undefined ? fallback : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

// eslint-disable-next-line react-refresh/only-export-components
export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

